### ISSUE TITLE
Streamlit Deployment Not Working!

### ISSUE THREAD

**Issue by dustin2551** [EswarDivi/DocuConverse#3]
In steamlit deployment it keeps saying the "Main file path" is missing. How to Fix this?

**Comment by EswarDivi** [comment]
Can you send me log or Error Message, so i can better understand it.

**Comment by dustin2551** [comment]
![Screenshot_5](https://github.com/EswarDivi/DocuConverse/assets/28645433/20c72555-66df-4125-bc7b-6eaaca2baeea)

**Comment by EswarDivi** [comment]
File Path should be

```
Talkwithpdf.py
```

**Comment by EswarDivi** [comment]
Make Sure you add these in Secrets of App settings with API key

```
hf_apikey="hf_"
cohere_apikey=""

```

**Comment by dustin2551** [comment]
> File Path should be
> 
> ```
> Talkwithpdf.py
> ```

Yeah,  I tried that and it didn't work.
